Implement NvAPI_GetAssociatedNvidiaDisplayHandle
jp7677/dxvk-nvapi pull request #175
Opened 2024-05-25 21:02 UTC by SveSop

This is needed to get the NVIDIA Tech demo "Apollo 11 Lunar Landing Demo" running. Downloaded from here: 
https://us.download.nvidia.com/downloads/cool_stuff/demos/Setup-Apollo-11-(1.05).exe

2024-05-25 21:30 UTC, SveSop commented
Did not make any "tests", as i am .. uhm.. not sure how that works i guess.

2024-05-26 06:06 UTC, jp7677 requested changes
Thanks for the PR, very cool and straight forward, nice.

Wrt having a test, it should be very similar to https://github.com/jp7677/dxvk-nvapi/blob/master/tests/nvapi_sysinfo_topo.cpp#L191. In fact, it should look like:

```c++
    SECTION("GetAssociatedNvidiaDisplayHandle succeeds") {
        NvDisplayHandle handle1 = nullptr;
        NvDisplayHandle handle2 = nullptr;
        NvDisplayHandle handle3 = nullptr;
        REQUIRE(NvAPI_EnumNvidiaDisplayHandle(0U, &handle1) == NVAPI_OK);
        REQUIRE(NvAPI_EnumNvidiaDisplayHandle(1U, &handle2) == NVAPI_OK);
        REQUIRE(NvAPI_EnumNvidiaDisplayHandle(2U, &handle3) == NVAPI_OK);

        NvDisplayHandle handle;

        REQUIRE(NvAPI_GetAssociatedNvidiaDisplayHandle("Output1", &handle) == NVAPI_OK);
        REQUIRE(handle == handle1);

        REQUIRE(NvAPI_GetAssociatedNvidiaDisplayHandle("Output2", &handle) == NVAPI_OK);
        REQUIRE(handle == handle2);

        REQUIRE(NvAPI_GetAssociatedNvidiaDisplayHandle("Output3", &handle) == NVAPI_OK);
        REQUIRE(handle == handle3);

        REQUIRE(NvAPI_GetAssociatedNvidiaDisplayHandle("Output4", &handle) == NVAPI_NVIDIA_DEVICE_NOT_FOUND);
    }
```

Could you also please prefix the commit message with `nvapi:`?

2024-05-26 06:06 UTC, jp7677 commented on src/nvapi.cpp
> +            return ExpectedDisplayHandle(n);
This should be `NvidiaDeviceNotFound`, from the header:

```
//! \retval NVAPI_INVALID_ARGUMENT         Either argument is NULL
//! \retval NVAPI_OK                      *pNvDispHandle is now valid
//! \retval NVAPI_NVIDIA_DEVICE_NOT_FOUND  No NVIDIA device maps to that display name

```

2024-05-26 13:21 UTC, jp7677 approved these changes

2024-05-26 13:22 UTC, merged